logging.level.com.reliaquest: DEBUG
service:
  employee:
    max_backoff_time: 120
    initial_backoff_time: 10
    baseurl: http://localhost:8112/api/v1/employee
spring.application.name: employee-api
server:
  port: 8111
  compression:
    enabled: true
